server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: security-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:h2:mem:security
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto:create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
